---
title: "👩‍💻 RLadies+ Ottawa"
---

## 💜 About RLadies+

[RLadies+](https://www.rladies.org) is a worldwide organization whose mission is to promote gender diversity in the R community. The R community suffers from an under-representation of minority genders (including but not limited to cis/trans women, trans men, non-binary, genderqueer, agender) in every role and area of participation, whether as leaders, package developers, conference speakers, conference participants, educators, or users.

## 🍁 About the Ottawa Chapter

```{r}
#| echo: false
#| include: false
# Get the current number of members on Meetup
library(rvest)
rladies <- read_html("https://www.meetup.com/rladies-ottawa/")
num_members <- rladies %>% 
  html_elements("a#member-count-link") %>%
  html_text()
num_members <- as.numeric(gsub("\\D", "", num_members))
```

This website is for the Ottawa chapter of RLadies+. The Ottawa chapter was founded in 2018. After the pandemic, RLadies+ Ottawa "rebooted" in September 2023. Today, the Ottawa chapter has `r num_members` members on [Meetup](https://www.meetup.com/rladies-ottawa/)!

## 🤝 Interested in joining?

:::{.callout-important}

## Important

**Please note that the mission of RLadies+ is to increase gender diversity in the R community.** While our Meetup Group is open to anyone to join, our events are intended to provide a safe space for women and gender minorities. Male allies may attend our in-person events **if they are invited by and accompanied by a woman or gender minority.**

:::

The best way to keep up to date with our upcoming events is to join [our Meetup Group](https://www.meetup.com/rladies-ottawa/). We post announcements regularly here!

If you are a woman or gender minority, we also recommend joining the [global RLadies+ directory](https://www.rladies.org/directory/) and the [RLadies+ Community Slack](https://guide.rladies.org/comm/slack/). This is a great way to connect with RLadies+ from other chapters!

If you're interested in being an organizer for RLadies+ Ottawa, please contact us through a direct message on our Meetup.

## 🎥 Recordings of past events

Some of our events are recorded and are posted on the [RLadies+ Global YouTube channel](https://www.youtube.com/@RLadiesGlobal). You can find the Ottawa chapter's videos under the ["RLadies+ Ottawa" playlist](https://www.youtube.com/watch?v=lFjjD0EEWX0&list=PLPwprT5wdzX5PwV2r0mAOw1CYkulwLpso).

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?si=e1yczlCqLxeFCnpz&amp;list=PLPwprT5wdzX5PwV2r0mAOw1CYkulwLpso" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
