---
title: "International Women's Day Data Challenge 2025"
---

R-Ladies Ottawa is hosting another data challenge to celebrate International Women's day 2025!!

::: {.callout-tip}
## Check out last year's submissions!

See the 2024 submissions and prompt [here](https://rladies-ottawa.github.io/events/2024/iwd.html#submissions)
:::


## The Challenge

At our `Posit::Conf` 2025 watch party we watched "GitHub: How To Tell Your Professional Story" by Abigail Haddad. In this presentation Haddad highlighted the importance of building a compelling porfolio that not only highlights your skills but explains your professional identity.

For this year's data challenge we encourage you to find YOUR passion project to round out your portfolio and develop your professional story! Take a look at your GitHub profile and ask yourself, *what type of project is missing here*? 

For example, if you participated in [last year's challenge](../events/2024/iwd.qmd) and created a traditional plot of some sort, this year try creating a visualization using a table, dashboard or another-outside-the-box presentation tool.


## Guidelines

Although this challenge is hosted by *R-Ladies* Ottawa, you don't have to use R to participate. You could use R, Python, a combination of the two, or anything you're comfortable with! 

No previous programming experience is required! If you're interested in participating, but aren't sure where to start, check out the recordings from our [Introduction to R workshops](https://rladies-ottawa.gitub.io/events/2024/intro_to_r.html) that we hosted in early 2024. The workshops will give you a solid foundation in data analysis and data visualization using R.

While anyone is welcome to participate in the challenge and submit an entry, **only submissions by women and gender minorities who reside in Canada will be eligible for the prizes.**

You can participate individually, or in teams of up to 5 people!

## Prizes

All participants will receive HexStickers! The most creative solution (selected by the R-Ladies Ottawa organizing team) will receive a $25 gift card to [Maker House](https://makerhouse.com/)!

## How to submit an entry

This will be a month-long data challenge, and you'll have until **April 4th** to submit your entry. Your submission can be in any form you like -- it can be a Quarto document, an image, a link to a webpage, or a link to a video, for example.

There are two options for submitting an entry: 

* Option 1 (preferred option): If you have experience with GitHub and Quarto, you can create a pull request on [this repository](https://github.com/RLadies-Ottawa/rladies-ottawa.github.io) and add your submission to the ["Submissions"](iwd.qmd#submissions) part of this page
* Option 2: If you don't have experience with GitHub, you can email ottawa@rladies.org a link to your submission materials and we will add the link to the ["Submissions"](iwd.qmd#submissions) part of this page

## Showcasing your analysis

After the submission deadline, R-Ladies Ottawa will host a virtual event where participants can showcase their work. This is a great way to learn from one another and to connect with other like-minded individuals!

The date and time of the showcase event will be announced soon.

## Submissions

Stay tuned!